# This is a basic workflow to help you get started with Actions

name: Testando o github Actions
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 16
      - run: npm cli
      - run: npm run test
